# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 596b6948c78e6684cbdf5cddb649e837799bd3fbadda7772a29e831b62015f4b46ba53630b3e4c71f39b5e2baf8fd870b1ed22fce6f75da7917f975ad8c7a68c

test:
  secret_key_base: 7d09c2df29e847aa3e0e80d73480d70749073d9f6ce74a1152e89514e0f33dfc474c71106e977ec009d71f2f0c75e30e68b11c924e7ed9963b262ee2c5ac2173

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
